name: Erlang build

on:
  pull_request:
    branches:
      - "*"

jobs:
  build:
    uses: valitydev/erlang-workflows/.github/workflows/erlang-simple-build.yml@v1.0.18
    with:
      otp-version: 27
      rebar-version: 3.24
      use-thrift: true
      thrift-version: 0.14.2.3
      run-eunit: false
      run-common-test: false
